name: "Terraform Check on Pull Request"

env:
  TERRAFORM_VERSION: 1.10.1

on:
  pull_request:
    paths:
      - '*.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate -no-color
