/*
aws_cloudwatch_log_group provides a CloudWatch Log Group resource for storing logs generated by ECS tasks or services.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group
*/
resource "aws_cloudwatch_log_group" "this" {
  name = "/ecs/${var.cluster_name}-cluster"

  tags = var.tags
}

/*
aws_ecs_cluster creates an ECS cluster where tasks and services can be deployed.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster
*/
resource "aws_ecs_cluster" "this" {
  name = "${var.cluster_name}-cluster"

  tags = var.tags
}
