name: Publish a Module to Public Registry

on:
  workflow_dispatch:
    inputs:
      module-path:
        description: 'Module path to process, e.g. `aws/acm'
        required: true
        type: string

env:
  # Secrets
  GH_APP_PRIVATE_KEY: ${{ secrets.SPARTAN_GH_APP_PRIVATE_KEY }}
  PAT_TOKEN: ${{ secrets.SPARTAN_PAT_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  # Variables
  GH_APP_ID: ${{ vars.SPARTAN_GH_APP_ID }}
  GH_APP_INSTALLATION_ID: ${{ vars.SPARTAN_GH_APP_INSTALLATION_ID }}
  GITHUB_ORG: ${{ vars.SPARTAN_GITHUB_ORG }}
  META_REPO_URL: ${{ vars.META_REPO_URL }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/set-up-repositories
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py --base-dir ${{ github.workspace }} --module-path ${{ inputs.module-path }}
