name: "Terraform Check on Pull Request"

env:
  TERRAFORM_VERSION: 1.10.1
  PLATFORMS: 'aws|gcp'                # delimiter should be "|"
  EXCLUDED_FOLDERS: 'examples|files'  # delimiter should be "|"

on:
  pull_request:

jobs:
  check_for_change:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.find_modules.outputs.modules }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 3

      - name: Get module directories
        id: find_modules
        run: |
          # Find changes between the current commit and its parent
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          
          # Iterate through changed files and determine affected modules
          CHANGED_MODULES=()
          for FILE in $CHANGED_FILES; do
              MODULE_NAME=$(dirname "$FILE")
              if echo "$MODULE_NAME" | grep -Eq "^($PLATFORMS)" && echo "$MODULE_NAME" | grep -Eqv "^($EXCLUDED_FOLDERS)"; then
                  CHANGED_MODULES+=( "$MODULE_NAME" )
              fi
          done
          # Sort and deduplicate module names
          DIRECTORIES=$(echo "${CHANGED_MODULES[@]}" | tr ' ' '\n' | sort -u)
          
          # Remove './' from the beginning of each directory
          DIRECTORIES=("${DIRECTORIES[@]//.\//}")
          
          # Convert to a valid JSON array format: compact (single line)
          DIRECTORIES_JSON=$(printf '%s\n' "${DIRECTORIES[@]}" | jq -R . | jq -sc .)
          echo "Changed module directories: $DIRECTORIES_JSON"
          echo "modules=$DIRECTORIES_JSON" >> "$GITHUB_OUTPUT"

  validate:
    runs-on: ubuntu-latest
    needs: check_for_change
    if: ${{ needs.check_for_change.outputs.modules != '' }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.check_for_change.outputs.modules) }}
      fail-fast: false
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ matrix.module }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
        working-directory: ${{ matrix.module }}

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ matrix.module }}
